### ISSUE TITLE
https://asset-packagist.org

### ISSUE THREAD

**Issue by FlorentTorregrosa** [unicorn-fail/drupal-bootstrap-styles#1]
Hello,

First, thanks for all your work done on the Bootstrap theme.

I wanted to add this repository in the require-dev section of the composer.json of my project because I think it would be easier to download a copy as mentioned in the doc https://drupal-bootstrap.org/api/bootstrap/docs!Sub-Theming.md/group/sub_theming/8.x-3.x

And also to have new versions detected with a 'composer outdated'.

I found https://asset-packagist.org/package/npm-asset/unicorn-fail--drupal-bootstrap-styles, but it is the compiled sources.

Also when adding it in Composer, I got the following warning: 

> Deprecation warning: require-dev.npm-asset/unicorn-fail--drupal-bootstrap-styles is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

Maybe it can be ignored as this package does not seem to be made for Composer.

So I am asking if it would be possible to have the sources of this repo available as a Composer package on packagist.org or asset-packagist.org?

**Comment by markhalliwell** [comment]
No, see https://www.drupal.org/project/bootstrap/issues/2852156#comment-13074151

**Comment by FlorentTorregrosa** [comment]
Ok. Thanks for the quick reply.
