### ISSUE TITLE
Form required marker is missing

### ISSUE THREAD

**Issue by markhalliwell** [unicorn-fail/drupal-bootstrap-styles#2]
Original issue/comment:
https://www.drupal.org/project/bootstrap/issues/3057980

By:
https://www.drupal.org/u/gorkagr

---

It seems that also in 3.19, the required marker in the forms is missing.

I have noticed that the css file drupal-bootstrap.min.css (view-source:https://cdn.jsdelivr.net/npm/@unicorn-fail/drupal-bootstrap-styles@0.0.1/dist/3.4.0/8.x-3.x/drupal-bootstrap.min.css) has the class :

```css
.form-required::after {
  background-image: url(../images/required.svg);
  //...
}
```

But the svg file requested is missing as the url of the file (https://cdn.jsdelivr.net/npm/@unicorn-fail/drupal-bootstrap-styles@0.0.1/dist/3.4.0/images/required.svg) cannot be found.

I have tried with 3.4.0 (and 3.4.1, but this one is missing), 3.3.7 and using CNDJS and the custom one, and all have same result (if the cache hasnt played with me, as it seems that always request the files from jsdelivr), the result is the same one.

In the previous version (3.17) this did not happen as the file was localy stored.

**Comment by markhalliwell** [comment]
We likely need to just replace this with inlined data. Optionally, we can just go back to a simple asterisk. Using the SVG was more to stay in line with how core removed the required marker from the theme system.

**Comment by gorkaguerrero** [comment]
Hi!

Not familiar with scss/less, but i assume that line 83 in `8.x-3.x/scss/drupal-bootstrap/component/_form.scss` should be changed in order to fix the issue.
If we add the svg inline, should be smth like :

```
.form-required:after {
width:10px;
height:10px; 
background-image:url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg"   width="10" height="10"><path d="m0 4.7956l0.70579-2.3173c1.6251 0.61065 2.8067 1.1377 3.5416 1.5839-0.19387-1.9688-0.29588-3.3229-0.30665-4.0623h2.2244c-0.031678 1.0764-0.14825 2.4264-0.35353 4.0461 1.0543-0.56482 2.2593-1.0872 3.6202-1.5671l0.70516 2.3166c-1.2988 0.45698-2.5723 0.76231-3.8191 0.91396 0.62343 0.57695 1.5028 1.6048 2.6394 3.0836l-1.8411 1.3878c-0.59238-0.85869-1.2931-2.0281-2.1009-3.5089-0.75648 1.5334-1.4217 2.7048-1.9938 3.5089l-1.8095-1.3878c1.186-1.5549 2.0344-2.5828 2.545-3.0836-1.3184-0.27095-2.571-0.57695-3.757-0.91396" style="fill:red;"/></svg>');
}
```
and we replace the dimensions for 10x10 (as is the svg i have added) in the width, height and background-size

I cannot try by myself as if I try to build/compile the repo as in the readme (with yarn), i get an error that does not allow me to continue or to compile anything:

```yarn run v1.16.0
✔ Versions.matching bootstrap 3.x.x (145ms)
✔ Versions.all bootstrap (121ms)

 bootstrap@3.1.1 
⠋ Bootstrap.install bootstrap (853μs)
⠋ Bootstrap.getPath bootstrap (563μs)
  fatal ReferenceError: name is not defined 
           at Bootstrap.getPath [as getPathAsync] (/Desktop/d8_bs/lib/Bootstrap.js:107:21)```

**Comment by user67x** [comment]
Oh I see the bug is closed. I haven’t understand what I should do, drupal/bootstrap is out with 3.20.0 version and the bug is always here.

**Comment by gorkaguerrero** [comment]
The release notes of drupal/bootstrap explain what to do.

https://www.drupal.org/project/bootstrap/releases/8.x-3.20

If you do that, it works (you may need to do cache rebuild couple times), but the marker is back
